default_platform(:ios)

platform :ios do
  desc "Upload Ahmed to TestFlight"
  lane :beta do
    build_app(
      project: "ios/App/App.xcodeproj",
      scheme: "App",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end
